language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: precise
      env:
        - CHECK_OLD_GPGME=1
    - dist: trusty
      env:
        - CHECK_OLD_GPGME=1
    - dist: xenial
    - os: osx
      brew_packages: gpgme
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - libgpgme11-dev
      - haveged
