language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: precise
      env:
        - CHECK_OLD_GPGME=1
    - dist: trusty
      env:
        - CHECK_OLD_GPGME=1
    - dist: xenial
    - os: osx
      brew_packages: gpgme
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_script: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - libgpgme11-dev
      - haveged

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

# Prevents Travis timeout for building gpg
before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &